### ISSUE TITLE
Lizard Doggo Spawning Broken

### ISSUE THREAD

**Issue by agargara** [AnthorNet/SC-InteractiveMap#348]
# Issue
Trying to spawn a lizard doggo results in an error.

## Replication
1. Right click a Foundation
2. Choose Spawn around...
3. Choose Lizard Doggo

### Actual Result
Chrome error console:
```
SCIM.js:2 Uncaught TypeError: Cannot read properties of null (reading 'pathName')
    at yi.loop (SCIM.js:2:527549)
    at yi.spawn (SCIM.js:2:526415)
    at new yi (SCIM.js:2:526307)
    at k.callback (SCIM.js:2:561955)
    at e.buttons.confirm.callback (SCIM.js:2:41638)
    at Me.processCallback (SCIM.js:2:50893)
    at HTMLButtonElement.<anonymous> (SCIM.js:2:38645)
    at HTMLDivElement.dispatch (jquery-3.4.1.min.js?v=1584077720:2:42571)
    at HTMLDivElement.<anonymous> (jquery-3.4.1.min.js?v=1584077720:2:40572)
```

Firefox error console: `Uncaught TypeError: s is null`

### Expected Result
A lizard doggo spawns.

### Possible fix
I was able to fix the issue by changing the pathName adding code to:
```
a.properties.push({
    name: "mFriendActor",
    type: "Object",
    value: {
        pathName: t + ".mFriendActor"
    }
}),
```

**Comment by AnthorNet** [comment]
Spawning fixed, not sure but they don't seems to move on my save
